version: '3.5'
services:
  # API
  unstuckoverflow-api-app:
    image: unstuckoverflow-api-app
    container_name: unstuckoverflow-api-app
    env_file:
      - api/.env
    build:
      context: api
      dockerfile: Dockerfile
    networks:
      - unstuckoverflow
    ports:
      - 9081:9081
      - 3081:3081
    restart: always
    depends_on:
      - unstuckoverflow-api-nginx
  unstuckoverflow-api-nginx:
    image: unstuckoverflow-api-nginx
    container_name: unstuckoverflow-api-nginx
    build:
      context: api
      dockerfile: Dockerfile.nginx
    networks:
      - unstuckoverflow
    ports:
      - 8081:8081
    restart: always

# UnstuckOverflow network
networks:
  unstuckoverflow:
    name: unstuckoverflow
    driver: bridge